# Revisit all the learning covered so far

## Numpy

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [5]:
c = np.array([10,20,30,40,50])
c

array([10, 20, 30, 40, 50])

In [6]:
# Addition of 1-D arrays

b + c

array([11, 22, 33, 44, 55])

In [7]:
# Subtraction of 1-D arrays

c - b

array([ 9, 18, 27, 36, 45])

In [8]:
# Multiplication of 1-D arrays

b * c

array([ 10,  40,  90, 160, 250])

In [9]:
# Division of 1-D arrays

c / b

array([10., 10., 10., 10., 10.])

In [10]:
# Squares or Powers

b **2

array([ 1,  4,  9, 16, 25])

In [11]:
np.power(b,3)

array([  1,   8,  27,  64, 125])

In [12]:
# 2-D arrays

d = np.array([[4,5,6], [7,8,9]])
d

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
e = np.array([[2,3,4], [4,5,6], [6,7,8]])
e

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# Array slicing

a[1::2]

array([1, 3, 5, 7, 9])

In [15]:
e[:2, 1:]

array([[3, 4],
       [5, 6]])

In [16]:
# Create an array of a particular sequence

f = np.arange(1,50,5)
f

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
# Create an ararnge of Zeroes

g = np.zeros((4,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# Create an identical matrix

h = np.eye(3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Create an arrange of ones

i = np.ones((3,2))
i

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# Create an array with a fixed value

j = np.full((4,3), 2.5)
j

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [37]:
# Create an arrange of empty values

k = np.empty((3,2))
k

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
# Create an array of linearly spaced values

l = np.linspace(10, 20, 3)
l

array([10., 15., 20.])

In [42]:
m = np.linspace(0,1,20)
m

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [43]:
# Create an array of random values

n = np.random.random((1,5))
n

array([[0.51755411, 0.01349577, 0.47265958, 0.51537602, 0.87354083]])

In [44]:
o = np.random.random(3)
o

array([0.00958272, 0.3901995 , 0.83273059])

In [45]:
# Create an array of random n values

p = np.random.randn(10)
p

array([ 1.85657922,  1.10431889, -0.24684496, -0.44306605,  0.77560872,
       -0.18396631,  0.264248  , -0.80141984,  1.27171577, -0.27489486])

## Python Dictionaries

In [46]:
import json

In [50]:
# Convert Json string to proper Json object

json_string = '{"Name": "Dileep", "Age": 34, "Location": "Dubai"}'
json.loads(json_string)

{'Name': 'Dileep', 'Age': 34, 'Location': 'Dubai'}

In [51]:
# Convert Json object back to Json String

json_object = {'Name': 'Dileep', 'Age': 34, 'Location': 'Dubai'}
json.dumps(json_object)

'{"Name": "Dileep", "Age": 34, "Location": "Dubai"}'

In [55]:
# Iterate a Json file

name = json_object["Name"]
age = json_object["Age"]
location = json_object["Location"]

f"Hi! This is Mr. {name}, of age {age} years, from {location}"

'Hi! This is Mr. Dileep, of age 34 years, from Dubai'

## Pandas

In [56]:
import pandas as pd

In [58]:
# Create a dataframe from a dictionary

dict1 = {
        "Name": ["Dileep", "Sachu", "Trinay"],
        "Age": [34, 32, 4],
        "DOB": ["1988-07-10", "1989-02-02", "2019-03-24"]
        }

df1 = pd.DataFrame(dict1)
df1

Name  Age         DOB
0  Dileep   34  1988-07-10
1   Sachu   32  1989-02-02
2  Trinay    4  2019-03-24

In [59]:
# Check the datatypes in the dataframe

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   DOB     3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [60]:
# Check the basic stats of the dataframe
df1.describe()

Age
count   3.000000
mean   23.333333
std    16.772994
min     4.000000
25%    18.000000
50%    32.000000
75%    33.000000
max    34.000000

In [62]:
# Slicing the dataframe using indexes

df1.iloc[1:]

Name  Age         DOB
1   Sachu   32  1989-02-02
2  Trinay    4  2019-03-24

In [63]:
df1.loc[0]

Name        Dileep
Age             34
DOB     1988-07-10
Name: 0, dtype: object

In [66]:
df1.loc[[0]]

Name  Age         DOB
0  Dileep   34  1988-07-10

In [64]:
df1['Name']

0    Dileep
1     Sachu
2    Trinay
Name: Name, dtype: object

In [65]:
df1[['Name']]

Name
0  Dileep
1   Sachu
2  Trinay

In [73]:
df1[df1["Age"] > 30]

Name  Age        DOB
0  Dileep   34 1988-07-10
1   Sachu   32 1989-02-02

In [74]:
df1["Age"].unique()

array([34, 32,  4])

In [75]:
df1["Age"].nunique()

3

In [76]:
df1["Age"].sum()

70

In [77]:
df1["Age"].mean()

23.333333333333332

In [78]:
df1["Age"].median()

32.0

In [79]:
df1["Age"].mode()

0     4
1    32
2    34
dtype: int64

In [69]:
# Data Manipulation: Convert DOB to a datetime

df1["DOB"] = pd.to_datetime(df1["DOB"])
df1.dtypes

Name            object
Age              int64
DOB     datetime64[ns]
dtype: object

In [80]:
# Import a csv file as Dataframe

df2 = pd.read_csv('/Users/dileepsathyan/Documents/GitHub/datasets/Churn_Modelling.xls')
df2.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [81]:
df2.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [83]:
# Check for any null values

df2.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [84]:
# List the columns of a Dataframe

df2.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [88]:
# Groupby certain columns to find the aggregates

df2[["Geography", "Gender", "EstimatedSalary"]].groupby(["Geography", "Gender"]).mean()

EstimatedSalary
Geography Gender                 
France    Female     99564.252755
          Male      100174.252495
Germany   Female    102446.424124
          Male       99905.033959
Spain     Female    100734.107475
          Male       98425.687680

In [92]:
# Group by and find multiple aggregate values of a field

df2[["Geography", "Gender", "EstimatedSalary"]].groupby(["Geography", "Gender"]).agg(["mean", "count", "sum"])

EstimatedSalary                    
                            mean count           sum
Geography Gender                                    
France    Female    99564.252755  2261  2.251148e+08
          Male     100174.252495  2753  2.757797e+08
Germany   Female   102446.424124  1193  1.222186e+08
          Male      99905.033959  1316  1.314750e+08
Spain     Female   100734.107475  1089  1.096994e+08
          Male      98425.687680  1388  1.366149e+08

In [94]:
# Resetting index

df3 = df2[["Geography", "Gender", "EstimatedSalary"]].groupby(["Geography", "Gender"]).agg(["mean", "count", "sum"])
df3 = df3.reset_index()
df3

Geography  Gender EstimatedSalary                    
                               mean count           sum
0    France  Female    99564.252755  2261  2.251148e+08
1    France    Male   100174.252495  2753  2.757797e+08
2   Germany  Female   102446.424124  1193  1.222186e+08
3   Germany    Male    99905.033959  1316  1.314750e+08
4     Spain  Female   100734.107475  1089  1.096994e+08
5     Spain    Male    98425.687680  1388  1.366149e+08

In [95]:
# Subsetting a dataframe

df3[df3["Geography"].isin(["France", "Spain"])]

Geography  Gender EstimatedSalary                    
                               mean count           sum
0    France  Female    99564.252755  2261  2.251148e+08
1    France    Male   100174.252495  2753  2.757797e+08
4     Spain  Female   100734.107475  1089  1.096994e+08
5     Spain    Male    98425.687680  1388  1.366149e+08

In [98]:
df3[df3["Gender"] == "Male"]

Geography Gender EstimatedSalary                    
                              mean count           sum
1    France   Male   100174.252495  2753  2.757797e+08
3   Germany   Male    99905.033959  1316  1.314750e+08
5     Spain   Male    98425.687680  1388  1.366149e+08

### Handle missing and Null values in a dataframe

In [102]:
from cmath import nan

dict2 = {
        'Gender': ['Male', nan, 'Female', nan, 'Female'],
        'Science': [85, nan, 72, 47, 53],
        'Maths': [56, nan, nan, 92, 68],
        'English': [nan, nan, 49, 82, 75]
        }

df4 = pd.DataFrame(dict2)
df4

Gender  Science  Maths  English
0    Male     85.0   56.0      NaN
1     NaN      NaN    NaN      NaN
2  Female     72.0    NaN     49.0
3     NaN     47.0   92.0     82.0
4  Female     53.0   68.0     75.0

In [104]:
# Check for the null values

df4.isnull().sum()

Gender     2
Science    1
Maths      2
English    2
dtype: int64

In [105]:
# Drop all the rows with at least 1 NULL value

df4.dropna()

Gender  Science  Maths  English
4  Female     53.0   68.0     75.0

In [106]:
# Fill the NULL values with an explicit value

df4.fillna("1")

Gender Science Maths English
0    Male      85    56       1
1       1       1     1       1
2  Female      72     1      49
3       1      47    92      82
4  Female      53    68      75

In [107]:
# Forward fill.

df4.fillna(method='ffill')

Gender  Science  Maths  English
0    Male     85.0   56.0      NaN
1    Male     85.0   56.0      NaN
2  Female     72.0   56.0     49.0
3  Female     47.0   92.0     82.0
4  Female     53.0   68.0     75.0

In [108]:
# Backward fill.

df4.fillna(method='bfill')

Gender  Science  Maths  English
0    Male     85.0   56.0     49.0
1  Female     72.0   92.0     49.0
2  Female     72.0   92.0     49.0
3  Female     47.0   92.0     82.0
4  Female     53.0   68.0     75.0

In [109]:
# Fill only a specific column

df4["Gender"].fillna("Not Given")

0         Male
1    Not Given
2       Female
3    Not Given
4       Female
Name: Gender, dtype: object

In [110]:
# Drop only the rows with ALL Null values

df4.dropna(how='all')

Gender  Science  Maths  English
0    Male     85.0   56.0      NaN
2  Female     72.0    NaN     49.0
3     NaN     47.0   92.0     82.0
4  Female     53.0   68.0     75.0

In [116]:
# Drop the columns with at least 1 NULL Value

df5 = pd.DataFrame({
                'Gender': ['Male', 'Male', 'Female', 'Male', 'Female'],
                'Science': [85, 86, 72, 47, 53],
                'Maths': [56, nan, nan, 92, 68],
                'English': [nan, nan, 49, 82, 75]
                })

df6 = df5.dropna(axis=1)
df6

Gender  Science
0    Male       85
1    Male       86
2  Female       72
3    Male       47
4  Female       53

In [117]:
# Finding the MIN of a field

df6["Science"].min()

47

In [118]:
# Finding the MAX of a field

df6["Science"].max()

86

In [119]:
# Finding the MEAN of a field

df6["Science"].mean()

68.6

In [120]:
# Finding the MEDIAN of a field

df6["Science"].median()

72.0

### Concatenating 2 dataframes

In [122]:
df7 = pd.DataFrame(
                {
                'Science': [85, 65, 72, 47, 53],
                'Maths': [56, 73, 66, 92, 68],
                'English': [54, 88, 49, 82, 75]
                })
df7

Science  Maths  English
0       85     56       54
1       65     73       88
2       72     66       49
3       47     92       82
4       53     68       75

In [123]:
df8 = pd.DataFrame(
                {
                'Science': [91, 48],
                'Maths': [75, 82],
                'English': [64, 95]
                })
df8

Science  Maths  English
0       91     75       64
1       48     82       95

In [125]:
pd.concat([df7, df8])

Science  Maths  English
0       85     56       54
1       65     73       88
2       72     66       49
3       47     92       82
4       53     68       75
0       91     75       64
1       48     82       95

In [126]:
df9 = pd.DataFrame(
                {
                'Hindi': [43, 32],
                'Biology': [67, 76],
                'Chemistry': [86, 76]
                })
df9

Hindi  Biology  Chemistry
0     43       67         86
1     32       76         76

In [130]:
pd.concat([df7, df8, df9], axis=0)

Science  Maths  English  Hindi  Biology  Chemistry
0     85.0   56.0     54.0    NaN      NaN        NaN
1     65.0   73.0     88.0    NaN      NaN        NaN
2     72.0   66.0     49.0    NaN      NaN        NaN
3     47.0   92.0     82.0    NaN      NaN        NaN
4     53.0   68.0     75.0    NaN      NaN        NaN
0     91.0   75.0     64.0    NaN      NaN        NaN
1     48.0   82.0     95.0    NaN      NaN        NaN
0      NaN    NaN      NaN   43.0     67.0       86.0
1      NaN    NaN      NaN   32.0     76.0       76.0

### Melting in dataframes

In [131]:
df8

Science  Maths  English
0       91     75       64
1       48     82       95

In [133]:
df8.melt()

variable  value
0  Science     91
1  Science     48
2    Maths     75
3    Maths     82
4  English     64
5  English     95

In [134]:
df_melted = df8.melt().rename(columns={'variable': 'Subject', 'value': 'Marks'})
df_melted

Subject  Marks
0  Science     91
1  Science     48
2    Maths     75
3    Maths     82
4  English     64
5  English     95

In [139]:
df_melted.pivot(columns='Subject', values='Marks')

Subject  English  Maths  Science
0            NaN    NaN     91.0
1            NaN    NaN     48.0
2            NaN   75.0      NaN
3            NaN   82.0      NaN
4           64.0    NaN      NaN
5           95.0    NaN      NaN

## Python Functions

In [151]:
def func1(arg):
    print(arg)


func1("Hello")

Hello


In [152]:
# When the number of arguments are arbitrary

def func2(*args):
    print(args)

    
func2(1,2,"Hello", 2.34)

(1, 2, 'Hello', 2.34)


In [153]:
# Keyword function

def func3(name, age):
    print(f"Hi {name}, You are {age} years old")
    

func3("Dileep", 34)

Hi Dileep, You are 34 years old


In [154]:
# Function inside another function.

def sumof2(a, b):
    return a + b


def sumprinter(p, q):
    sum = sumof2(p, q)
    print(sum)
    
    
sumprinter(10, 3)

13


In [158]:
# Nested Functions

def doubler(num):
    print(num * 2)
    

for i in range(1, 5):
    doubler(i)

2
4
6
8


In [165]:
# recursive function: A function which calls itself within the function.


def recursive_func(num):
    if num == 10:
        print(num)
        print('Process completed...')
    else:
        print(num)
        recursive_func(num+1)
        
recursive_func(8)

8
9
10
Process completed...


In [ ]:
# Lamda functions

