# Revisit all the learning covered so far

## Numpy

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [5]:
c = np.array([10,20,30,40,50])
c

array([10, 20, 30, 40, 50])

In [6]:
# Addition of 1-D arrays

b + c

array([11, 22, 33, 44, 55])

In [7]:
# Subtraction of 1-D arrays

c - b

array([ 9, 18, 27, 36, 45])

In [8]:
# Multiplication of 1-D arrays

b * c

array([ 10,  40,  90, 160, 250])

In [9]:
# Division of 1-D arrays

c / b

array([10., 10., 10., 10., 10.])

In [10]:
# Squares or Powers

b **2

array([ 1,  4,  9, 16, 25])

In [11]:
np.power(b,3)

array([  1,   8,  27,  64, 125])

In [12]:
# 2-D arrays

d = np.array([[4,5,6], [7,8,9]])
d

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
e = np.array([[2,3,4], [4,5,6], [6,7,8]])
e

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# Array slicing

a[1::2]

array([1, 3, 5, 7, 9])

In [15]:
e[:2, 1:]

array([[3, 4],
       [5, 6]])

In [16]:
# Create an array of a particular sequence

f = np.arange(1,50,5)
f

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
# Create an ararnge of Zeroes

g = np.zeros((4,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# Create an identical matrix

h = np.eye(3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Create an arrange of ones

i = np.ones((3,2))
i

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# Create an array with a fixed value

j = np.full((4,3), 2.5)
j

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [37]:
# Create an arrange of empty values

k = np.empty((3,2))
k

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
# Create an array of linearly spaced values

l = np.linspace(10, 20, 3)
l

array([10., 15., 20.])

In [42]:
m = np.linspace(0,1,20)
m

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [43]:
# Create an array of random values

n = np.random.random((1,5))
n

array([[0.51755411, 0.01349577, 0.47265958, 0.51537602, 0.87354083]])

In [44]:
o = np.random.random(3)
o

array([0.00958272, 0.3901995 , 0.83273059])

In [45]:
# Create an array of random n values

p = np.random.randn(10)
p

array([ 1.85657922,  1.10431889, -0.24684496, -0.44306605,  0.77560872,
       -0.18396631,  0.264248  , -0.80141984,  1.27171577, -0.27489486])

## Python Dictionaries

In [46]:
import json

In [50]:
# Convert Json string to proper Json object

json_string = '{"Name": "Dileep", "Age": 34, "Location": "Dubai"}'
json.loads(json_string)

{'Name': 'Dileep', 'Age': 34, 'Location': 'Dubai'}

In [51]:
# Convert Json object back to Json String

json_object = {'Name': 'Dileep', 'Age': 34, 'Location': 'Dubai'}
json.dumps(json_object)

'{"Name": "Dileep", "Age": 34, "Location": "Dubai"}'

In [55]:
# Iterate a Json file

name = json_object["Name"]
age = json_object["Age"]
location = json_object["Location"]

f"Hi! This is Mr. {name}, of age {age} years, from {location}"

'Hi! This is Mr. Dileep, of age 34 years, from Dubai'